// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                int32
	UserId            int32
	Type              string
	Provider          string
	ProviderAccountId string
	RefreshToken      pgtype.Text
	AccessToken       pgtype.Text
	ExpiresAt         pgtype.Int8
	IDToken           pgtype.Text
	Scope             pgtype.Text
	SessionState      pgtype.Text
	TokenType         pgtype.Text
}

type Session struct {
	ID           int32
	UserId       int32
	Expires      pgtype.Timestamptz
	SessionToken string
}

type User struct {
	ID            int32
	Name          pgtype.Text
	Email         pgtype.Text
	EmailVerified pgtype.Timestamptz
	Image         pgtype.Text
}
