// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT users.id, users.email, sessions.expires
FROM sessions
JOIN users ON users.id = sessions."userId"
WHERE sessions."sessionToken" = $1
`

type GetSessionWithUserRow struct {
	ID      int32
	Email   pgtype.Text
	Expires pgtype.Timestamptz
}

func (q *Queries) GetSessionWithUser(ctx context.Context, sessiontoken string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, sessiontoken)
	var i GetSessionWithUserRow
	err := row.Scan(&i.ID, &i.Email, &i.Expires)
	return i, err
}
