import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { GeistPixelTriangle, GeistPixelSquare } from "geist/font/pixel";
import "./globals.css";

const geistSans = GeistSans;
const geistMono = GeistMono;
const geistPixelTriangle = GeistPixelTriangle;
const geistPixelSquare = GeistPixelSquare;
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${geistPixelSquare.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
